### PR TITLE
Set the module ID to the file name w/o extensions

### PR DESCRIPTION
**Pull request by stormsilver**
This allows us to reference files with multiple extensions like `foo.es6.erb`
as `foo` instead of `foo.es6`

### CODE REVIEW

**Comment by TannerRogalsky** [comment]
@stormsilver This looks useful. Could you add a test for this?

**Comment by stormsilver** [comment]
@TannerRogalsky Yikes, I didn't even run the tests before :sob: 

I moved the test fixture `mod.es6` -> `mod.es6.erb`. It appears that module IDs are now _always_ included, so there is some redundancy in the tests. I'm not sure if this is desirable or correct (I have very little Babel experience)

**Comment by TannerRogalsky** [comment]
Hmm, yeah, it seems like Babel will assume that the `moduleIds` option is true if you pass a `moduleId` option. While that makes sense, it's probably not ideal for our use case. Do you mind only passing `moduleId` if `moduleIds` is true?

**Comment by stormsilver** [comment]
@TannerRogalsky definitely. I thought about doing that at first but wanted to run it by you first.

See how you feel about this version. I ended up not writing a specific test for this since appending another file extension to the fixture name caused the existing tests to fail without my change. Let me know if there's anything else you'd like to see changed!

**Comment by TannerRogalsky** [comment]
:+1: Thanks for the pull request and updates! I will push a new version of this gem.

**Comment by TannerRogalsky** [comment]
Published in version 0.7.0: https://rubygems.org/gems/sprockets-es6/versions/0.7.0

**Pull request merged**
