### PR TITLE
Resolve moduleRoot regression

### PR DESCRIPTION
**Pull request by TannerRogalsky**
See #6.

@bradleypriest, I hope that this resolves your issue without needing to move backward on #4.

### CODE REVIEW

**Comment by bradleypriest** [comment]
My other thought was to support `moduleId = auto` or similar. It feels like we're over stepping by setting auto setting the moduleId when you set moduleIds

**Comment by TannerRogalsky** [comment]
I can understand that concern but I also think that this is generally what that setting is intended for. Unless you can think of a use-case that isn't covered by the current implementation, I'm inclined toward a simpler API.

**Comment by bradleypriest** [comment]
It just seems like we're unnecessarily duplicating babel api. As a new developer I wouldn't be expecting you to set extra options for me. 

Maybe a separate option that doesn't get overwrite a default babel option then i.e. options['setOptionId']?

—
Bradley Priest

**Comment by TannerRogalsky** [comment]
If you explicitly set `moduleId` (although I can't imagine why you would in the context of this gem), it will not be overwritten. We only use conditional assignment when setting `moduleId`.

I don't love the code smell of the implementation surrounding `moduleIds` but, for the time being, I consider it adequate. 

Thanks for your input and PRs!

**Comment by bradleypriest** [comment]
If this is going into Rails core, I really want to reiterate that I strongly believe that it should be opt-in rather than a side-effect to have `moduleId` set.
Are you completely against the idea?

**Comment by TannerRogalsky** [comment]
@bradleypriest Not at all! The current implementation is functional but there is no love lost between it and myself. I also didn't consider that this code would be copied verbatim into Rails core...

If you would consider opening a PR with your proposal, I'd be much obliged.

**Pull request merged**
