### PR TITLE
Allow newer sprockets versions

### PR DESCRIPTION
**Pull request by leifcr**

### CODE REVIEW

**Comment by mickey** [comment]
:+1:

**Comment by seekshiva** [comment]
:+1:

**Comment by aliou** [comment]
:+1:

**Comment by tough-griff** [comment]
:+1:

**Comment by blackjk3** [comment]
Any chance this could get merged? For those of us using sprockets 3.1.0 it would help us out :)

**Comment by iancanderson** [comment]
yes please! :+1:

**Comment by dalpo** [comment]
:+1:

**Comment by digitalcora** [comment]
@TannerRogalsky Is there anything more that needs to be done to bump the dependency version? `sprockets-es6` seems to be the most widely-recommended way of using ES6 in the asset pipeline (at least until Sprockets 4 has a pre-release), but right now it locks Sprockets to old beta versions.

**Comment by TannerRogalsky** [comment]
Sorry about the delay! https://rubygems.org/gems/sprockets-es6/versions/0.6.2

**Comment by leifcr** [comment]
Awesome. Thanks!

**Pull request merged**
